In [0]:
import numpy as np 
import gym
import random

In [5]:
env = gym.make('Taxi-v2')
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [12]:
action_size = env.action_space.n
print('number of possible actions is: {}'.format(action_size))
state_size = env.observation_space.n
print('number of possible states is: {}'.format(state_size))

number of possible actions is: 6
number of possible states is: 500


In [14]:
qtable = np.zeros((state_size,action_size))
print('Current Q Table:')
print(qtable)

Current Q Table:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [0]:
total_episodes = 50000        # Total episodes
total_test_episodes = 100     # Total test episodes
max_steps = 99                # Max steps per episode

learning_rate = 0.7           # Learning rate
gamma = 0.618                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01          

In [0]:
for episode in range(total_episodes):
  state = env.reset()
  step = 0
  done = False 
  
  for step in range(max_steps):
    explore_exploit = random.uniform(0,1)
    if explore_exploit > epsilon:
      action = np.argmax(qtable[state,:])
    else:
      action = env.action_space.sample()
    
    new_s, reward, done, info = env.step(action)
    
    qtable[state,action] += learning_rate*(reward+gamma*np.max(qtable[new_s,:])-qtable[state,action])
    state = new_s
    
    if done:
      break
  episode +=1
  epsilon = min_epsilon + (max_epsilon-min_epsilon) * np.exp(-decay_rate*episode)

In [19]:
qtable

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ -1.89494485,  -1.44814804,  -1.89494849,  -1.52595865,
         -0.72512948, -10.44964736],
       [ -0.72516057,   0.44459665,  -0.76861951,   0.44459614,
          2.33782249,  -8.56289032],
       ...,
       [ -2.08151226,   5.39938776,  -2.13185905,  -2.07194581,
         -9.1       ,  -9.7953664 ],
       [ -2.49766782,  -1.44920753,  -2.50404421,  -2.47180639,
        -11.2246066 ,  -7.        ],
       [ 18.37384858,  10.35761079,  18.22348897,  31.35602094,
          9.24535897,   9.37801224]])