In [0]:
import numpy as np
import gym
import random

In [2]:
env = gym.make('FrozenLake-v0')
env.render()


SFFF
FHFH
FFFH
HFFG


/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [3]:
n_actions = env.action_space.n
n_states = env.observation_space.n
print('Number of actions: {}'.format(n_actions))
print('Number of states: {}'.format(n_states))

Number of actions: 4
Number of states: 16


In [0]:
qtable = np.zeros((n_states,n_actions))

In [0]:
total_episodes = 15000        # Total episodes
total_test_episodes = 100     # Total test episodes
max_steps = 99                # Max steps per episode

learning_rate = 0.5           # Learning rate
gamma = 0.95                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.1

In [23]:
rewards = []
for episode in range(total_episodes):
  state = env.reset()
  total_rewards = 0
  for step in range(max_steps):
    exp_exp = random.uniform(0,1)
    if exp_exp < epsilon:
      action = env.action_space.sample()
    else:
      action = np.argmax(qtable[state,:])
    new_s, reward, done, info = env.step(action)
    qtable[state,action] += learning_rate*(reward+gamma*np.max(qtable[new_s,:])-qtable[state,action])
    state = new_s
    total_rewards += reward
    if done:
      break
  
  episode +=1
  epsilon = min_epsilon + (max_epsilon-min_epsilon) * np.exp(-decay_rate*episode)
  rewards.append(total_rewards)
print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)    

Score over time: 0.5382666666666667
[[2.76039617e-01 1.08744907e-01 1.55731192e-01 1.30492202e-01]
 [3.60849072e-02 4.02008710e-02 2.24515517e-02 1.41361311e-01]
 [7.24798235e-02 2.09678227e-02 2.89015407e-02 2.98270997e-02]
 [2.19029930e-02 1.58797598e-02 7.82810150e-03 2.88085650e-02]
 [3.24915175e-01 3.51917527e-02 8.38078947e-02 3.18182861e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.84499370e-03 2.22129474e-04 3.65366204e-02 2.65510028e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.82641605e-01 2.83430007e-01 5.11868391e-02 4.43790860e-01]
 [1.15647973e-01 4.10878360e-01 7.77917122e-02 3.40503370e-01]
 [5.30442554e-01 4.77333907e-02 4.65501190e-02 4.95792297e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.31565090e-01 9.93516213e-02 5.59384638e-01 1.77743507e-01]
 [3.53832669e-01 8.54366399e-01 3.67520696e-01 4.85290903e-01]
 [0.00000000e+00 0.

In [25]:
env.reset()

for episode in range(10):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 50
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 5
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 8
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 32
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 20
****************************************************
EPISODE  5
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 33
****************************************************
EPISODE  6
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 37
****************************************************
EPISODE  7
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 14
****************************************************
EPISODE  8
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of st